name: Deploy Sanity

on:
  push:
    branches-ignore:
      - "main"

jobs:
  pr-lint-build:
    name: Run lint and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: cd .\sanity\
      - run: npm install -D @sanity/cli
      - run: npm run ci
      - run: npm run deploy
