name: Deploy Sanity

on:
  push:
    branches:
      - "main"

jobs:
  pr-lint-build:
    name: Run lint and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sanity

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -D @sanity/cli
      - run: npm i
      - run: SANITY_AUTH_TOKEN=${{ env.SANITY_AUTH_TOKEN }} npm run deploy
